---
- name: Installation role users
  hosts: all
  become: yes
  vars:
           db_user: caux
           db_password: caux
           db_name: caux
  roles:
          - apache
          - postgresql
          - php
